# Generated by Django 4.2.3 on 2023-09-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('keywords', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Data de atualização')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Data de criação')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('subtitle', models.CharField(max_length=250, verbose_name='SubTitulo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('waiting_publication', 'Aguardando publicação'), ('published', 'Publicado'), ('canceled', 'Cancelado')], default='waiting_publication', max_length=50, verbose_name='Status')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visível')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='a_authors', to='author.author', verbose_name='Categoria')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_categories', to='categories.category', verbose_name='Categoria')),
                ('keywords', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_keywords', to='keywords.keyword', verbose_name='Palavras-chave')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
