# Generated by Django 4.2.3 on 2023-09-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_options'),
        ('articles', '0004_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='a_authors', to='author.author', verbose_name='Author'),
        ),
    ]
